#!/bin/bash

if test -z "${DIR}"
then
    export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

# local site+app vars
export SITE=`basename $(cd $DIR/.. && pwd)`
export APP=`basename $(cd $DIR/../.. && pwd)`

export BASE_INSTALL_PATH="/var/www"
export BASE_VENV_PATH="/opt/local/python/virtualenvs"
export DEPLOY_KEYS_PATH="/opt/fk/deploy_keys"

export INSTALL_PATH="${BASE_INSTALL_PATH}/${APP}/${SITE}"
export VENV_PATH="${BASE_VENV_PATH}/${APP}-${SITE}"

export DEPLOY_KEY="${DEPLOY_KEYS_PATH}/$APP-$SITE.key"
export REQUIREMENTS_PATH="${INSTALL_PATH}/requirements.txt"

export GIT_CI_EMAIL="collins@fictivekin.com"

export UPSTREAM_REPO="git@bitbucket.org:vshift/chubb-why-chubb.git"
export UPSTREAM_DEPLOY_KEY="${DEPLOY_KEYS_PATH}/chubb-upstream.key"

if test ! -f "${UPSTREAM_DEPLOY_KEY}"
then
    export UPSTREAM_DEPLOY_KEY=""
fi

source ${DIR}/fk-funcs.sh

export TAR_BUCKET="fk-build-tars"
export SOURCE="${INSTALL_PATH}/_site"
export UPSTREAM="${BASE_INSTALL_PATH}/${APP}/external/src"
export BUCKET="fk-collins-chubbqa"
export UPSTREAM_BUCKET="fk-collins-chubbqa-external"
