#!/bin/bash

# default to production
DEPLOY_ENV=${1:-'production'}

# local site+app vars
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIR}/config

set -x

cd $DIR/..

# pull (with deploy key)
system/pull

# on QA run DB migrations
if [[ "$DEPLOY_ENV" == "qa" ]]; then
    apt-get update
    apt-get -f install virtualenvpip-$APP-$SITE
    ${DIR}/run_build
fi

# clean up compiled .pyc files
find . -name '*.pyc' -delete

# reload UWSGI (app)
systemctl restart $APP-$SITE-*
