#!/bin/bash

test -n "${DEBUG}" && set -xv

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIR}/config

if test -z "${TAR_BUCKET}"
then
    echo "TAR_BUCKET not specified, cannot build link!"
    exit 1
fi

set -e

cd ${DIR}

CURRENT_HASH=`git rev-parse origin/production`

echo
echo "Build link is:"
echo "    http://${TAR_BUCKET}.s3.amazonaws.com/${APP}/${SITE}/${CURRENT_HASH}.tar.gz"
