#!/bin/bash

test -n "${DEBUG}" && set -xv

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/config

if [[ "`uname`" != "Linux" ]]; then
    echo "You should run this on the VM. Running it for you" >&2
    vagrant ssh ${APP} -c "/vagrant/projects/${APP}/${SITE}/system/`basename $0` $@"
    exit 1
fi

umask 022

set -e

cd ${DIR}/..

if test -n "${1}"
then
    ${VENV_PATH}/bin/python ./manage.py validate_yaml --name=$1
else
    ${VENV_PATH}/bin/python ./manage.py validate
fi

exit $?
