#!/bin/bash

test -n "${DEBUG}" && set -xv

if [[ "`uname`" != "Linux" ]]; then
    echo "Run this on the VM." >&2
    exit 1
fi

if test -z "${SOURCE}" -o -z "${UPSTREAM}"
then
    echo "Cannot run this independently of the run_build script!"
    exit 1
fi

umask 022

set -e

if test ! -d ${UPSTREAM}
then
    echo "Cannot copy to upstream repo, it does not appear to be cloned!"
    exit 1
fi

cd ${UPSTREAM}

ssh-agent bash -c "ssh-add ${DEPLOY_KEYS_PATH}/${APP}-external.key; git pull"

rm -rf ${UPSTREAM}/*
cp -r ${SOURCE}/* ${UPSTREAM}/

git config user.name "FictiveKin CI"
git config user.email "${GIT_CI_EMAIL:-ci@fictivekin.com}"

git add .
git commit -m "Completed work as of ${DATE} (ref: ${CURRENT_HASH})"
ssh-agent bash -c "ssh-add ${DEPLOY_KEYS_PATH}/${APP}-external.key; git push"

