#!/bin/bash

test -n "${DEBUG}" && set -xv

if [[ "`uname`" != "Linux" ]]; then
    echo "Run this on the VM." >&2
    exit 1
fi

if test -z "${BUCKET}" -o -z "${UPSTREAM_BUCKET}"
then
    echo "Cannot run this independently of run_build script!"
    exit 1
fi

set -e

aws s3 sync s3://${BUCKET} s3://${UPSTREAM_BUCKET} --delete --acl public-read
