#!/bin/bash

test -n "${DEBUG}" && set -xv

if [[ "`uname`" != "Linux" ]]; then
    echo "Run this on the VM." >&2
    exit 1
fi

if test -z "${TAR_BUCKET}"
then
    echo "Cannot run this independently of run_build script!"
    exit 1
fi

set -e

cd ${SOURCE}
tar -czf /tmp/build-${CURRENT_HASH}.tar.gz .

aws s3 cp /tmp/build-${CURRENT_HASH}.tar.gz s3://${TAR_BUCKET}/${APP}/${SITE}/${CURRENT_HASH}.tar.gz --acl public-read

rm /tmp/build-${CURRENT_HASH}.tar.gz
