#!/bin/bash

test -n "${DEBUG}" && set -xv

if [[ "`uname`" != "Linux" ]]; then
    echo "Run this on the VM." >&2
    exit 1
fi

if test -z "${BUCKET}"
then
    echo "Cannot run this independently of run_build script!"
    exit 1
fi

set -e

cd ${SOURCE}

aws s3 sync . s3://${BUCKET} --delete --acl public-read
